version: '3'
services:
  maestro:
    image: scatteredplayers/maestro:x86
    environment: 
      - PORT=80
    ports:
      - '80:80'
    volumes:
      - '/mnt/secret/service-secrets:/usr/src/maestro/secrets'