version: '3'
services:
  mongo:
    image: mongo:latest
    environment: 
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - '27017:27017'
    volumes:
      - '/mnt/mongodb/data/configdb:/data/configdb'
      - '/mnt/mongodb/data/db:/data/db'
      - '/mnt/mongodb/log:/log'
      - '/mnt/mongodb/journal:/journal'
      - '/mnt/secret/service-secrets:/secrets'