version: '2'
services:
  janus:
    restart: unless-stopped
    image: scatteredplayers/janus:main
    network_mode: host
    volumes:
      - '/mnt/secret/letsencrypt:/etc/letsencrypt'
      - '/mnt/secret/janus-conf:/etc/janus'